# ECON N171: Economic Development
## Lecture 3 — Pandas I: Working with Real-World Data
**Instructor: Rajveer Jat | Summer 2026**

---

## Learning Objectives

By the end of this notebook, you will be able to:

1. Understand what a **DataFrame** is and why it is the workhorse of data analysis
2. Create DataFrames from scratch and load them from CSV files
3. **Inspect** a dataset — shape, types, missing values, basic summaries
4. **Select** columns and rows using labels and positions
5. **Filter** rows using conditions
6. **Sort** and **rank** data

> 💡 Run each cell with `Shift + Enter` and follow along.

---
## Part 1: What is Pandas?

NumPy is great for arrays of numbers. But real economic datasets have:
- **Mixed types** — country names (strings) alongside GDP (floats) and year (int)
- **Column labels** — variables have names, not just positions
- **Missing values** — not every country reports every indicator
- **Row labels** — observations have identifiers

**Pandas** handles all of this through its core object: the **DataFrame** — essentially a spreadsheet inside Python.

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.2.2

---
## Part 2: Creating a DataFrame

The most common way: from a Python dictionary where **keys are column names** and **values are lists**.

In [2]:
# Build our 12-country development dataset as a DataFrame
data = {
    'country'       : ['USA', 'France', 'Japan', 'UAE',
                       'Brazil', 'Mexico', 'South Korea',
                       'Vietnam', 'Nigeria', 'Ghana',
                       'Ethiopia', 'Kenya'],

    'region'        : ['North America', 'Europe', 'East Asia', 'Middle East',
                       'Latin America', 'Latin America', 'East Asia',
                       'East Asia', 'Sub-Saharan Africa', 'Sub-Saharan Africa',
                       'Sub-Saharan Africa', 'Sub-Saharan Africa'],

    'income_group'  : ['High', 'High', 'High', 'High',
                       'Upper-Middle', 'Upper-Middle', 'High',
                       'Lower-Middle', 'Lower-Middle', 'Lower-Middle',
                       'Low', 'Low'],

    'gdp_per_capita': [76399.0, 40886.0, 33815.0, 49532.0,
                        9000.5,  9926.0, 32255.0,
                        4163.5,  2065.8,  2363.0,
                         925.1,  1838.0],

    'population'    : [333271341,  67897000, 125124989,   9890400,
                       215313498, 127504125,  51628117,
                        97468029, 218541000,  32395450,
                       123380000,  54027487],

    'poverty_rate'  : [1.2, 0.1, 0.7, 0.0,
                       5.8, 7.3, 0.2,
                       1.5, 39.1, 24.8,
                       26.1, 36.1],

    'growth_rate'   : [2.0, 2.5, 1.5, 3.5,
                       3.0, 2.5, 2.7,
                       6.1, 3.2, 3.8,
                       7.0, 5.2],

    'year'          : [2022] * 12
}

df = pd.DataFrame(data)
df

,country,region,income_group,gdp_per_capita,population,poverty_rate,growth_rate,year
0,USA,North America,High,76399.0,333271341,1.2,2.0,2022
1,France,Europe,High,40886.0,67897000,0.1,2.5,2022
2,Japan,East Asia,High,33815.0,125124989,0.7,1.5,2022
3,UAE,Middle East,High,49532.0,9890400,0.0,3.5,2022
4,Brazil,Latin America,Upper-Middle,9000.5,215313498,5.8,3.0,2022
5,Mexico,Latin America,Upper-Middle,9926.0,127504125,7.3,2.5,2022
6,South Korea,East Asia,High,32255.0,51628117,0.2,2.7,2022
7,Vietnam,East Asia,Lower-Middle,4163.5,97468029,1.5,6.1,2022
8,Nigeria,Sub-Saharan Africa,Lower-Middle,2065.8,218541000,39.1,3.2,2022
9,Ghana,Sub-Saharan Africa,Lower-Middle,2363.0,32395450,24.8,3.8,2022
10,Ethiopia,Sub-Saharan Africa,Low,925.1,123380000,26.1,7.0,2022
11,Kenya,Sub-Saharan Africa,Low,1838.0,54027487,36.1,5.2,2022

Notice: Pandas displays this as a clean table — row indices on the left, column names on top. This is a **DataFrame**.

---
## Part 3: Inspecting a Dataset

The first thing you always do with a new dataset: **look at it carefully before touching it.**

In [3]:
# Shape: (rows, columns)
print("Shape:", df.shape)
print(f"  → {df.shape[0]} countries, {df.shape[1]} variables")

Shape: (12, 8)
  → 12 countries, 8 variables

In [4]:
# Column names and data types
print(df.dtypes)

country            object
region             object
income_group       object
gdp_per_capita    float64
population          int64
poverty_rate      float64
growth_rate       float64
year                int64
dtype: object

In [5]:
# First and last few rows
print("--- First 4 rows ---")
display(df.head(4))

print("--- Last 4 rows ---")
display(df.tail(4))

--- First 4 rows ---

,country,region,income_group,gdp_per_capita,population,poverty_rate,growth_rate,year
0,USA,North America,High,76399.0,333271341,1.2,2.0,2022
1,France,Europe,High,40886.0,67897000,0.1,2.5,2022
2,Japan,East Asia,High,33815.0,125124989,0.7,1.5,2022
3,UAE,Middle East,High,49532.0,9890400,0.0,3.5,2022

--- Last 4 rows ---

,country,region,income_group,gdp_per_capita,population,poverty_rate,growth_rate,year
8,Nigeria,Sub-Saharan Africa,Lower-Middle,2065.8,218541000,39.1,3.2,2022
9,Ghana,Sub-Saharan Africa,Lower-Middle,2363.0,32395450,24.8,3.8,2022
10,Ethiopia,Sub-Saharan Africa,Low,925.1,123380000,26.1,7.0,2022
11,Kenya,Sub-Saharan Africa,Low,1838.0,54027487,36.1,5.2,2022

In [6]:
# Statistical summary of all numeric columns
df.describe().round(2)

       gdp_per_capita    population  poverty_rate  growth_rate    year
count           12.00  1.200000e+01         12.00        12.00    12.0
mean         21930.74  1.213701e+08         11.91         3.58  2022.0
std          24467.41  9.361396e+07         15.13         1.68     0.0
min            925.10  9.890400e+06          0.00         1.50  2022.0
25%           2288.70  5.342764e+07          0.57         2.50  2022.0
50%           9463.25  1.104240e+08          3.65         3.10  2022.0
75%          35582.75  1.494565e+08         25.12         4.15  2022.0
max          76399.00  3.332713e+08         39.10         7.00  2022.0

In [7]:
# Missing values — critical check before any analysis
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing: {df.isnull().sum().sum()}")

Missing values per column:
country           0
region            0
income_group      0
gdp_per_capita    0
population        0
poverty_rate      0
growth_rate       0
year              0
dtype: int64

Total missing: 0

In [8]:
# Now let's introduce a missing value to see how it looks
df_with_missing = df.copy()
df_with_missing.loc[8, 'poverty_rate'] = np.nan   # Nigeria's poverty rate is missing
df_with_missing.loc[10, 'growth_rate'] = np.nan   # Ethiopia's growth rate is missing

print("Missing values after introducing NaNs:")
print(df_with_missing.isnull().sum())

Missing values after introducing NaNs:
country           0
region            0
income_group      0
gdp_per_capita    0
population        0
poverty_rate      1
growth_rate       1
year              0
dtype: int64

In [9]:
# Unique values in categorical columns
print("Income groups:", df['income_group'].unique())
print("Regions:",       df['region'].unique())
print()
print("Countries per income group:")
print(df['income_group'].value_counts())

Income groups: ['High' 'Upper-Middle' 'Lower-Middle' 'Low']
Regions: ['North America' 'Europe' 'East Asia' 'Middle East' 'Latin America'
 'Sub-Saharan Africa']

Countries per income group:
income_group
High            5
Lower-Middle    3
Upper-Middle    2
Low             2
Name: count, dtype: int64

---
## Part 4: Loading Real Data from the World Bank

In practice, we load data from files or APIs — not type it by hand.  
Let's pull real World Bank data using the `wbgapi` library.

In [10]:
# Install World Bank API (only needed once in Colab)
!pip install wbgapi -q

In [12]:
import wbgapi as wb

# Download GDP per capita (current USD) for all countries, 2000-2022
# Indicator: NY.GDP.PCAP.CD
gdp_wb = wb.data.DataFrame('NY.GDP.PCAP.CD',
                             time=range(2000, 2023),
                             labels=True)

# Clean up column names
gdp_wb.columns = [str(c).replace('YR', '') for c in gdp_wb.columns]
gdp_wb = gdp_wb.reset_index()

print("Shape:", gdp_wb.shape)
gdp_wb.head()

Shape: (266, 25)

,economy,Country,2000,2001,2002,2003,2004,2005,2006,2007,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,ZWE,Zimbabwe,562.833757,566.388746,524.936479,468.471933,469.719299,461.271388,431.034994,413.521245,...,1362.994983,1372.915262,1387.126326,1408.139453,3445.449410,2270.895319,2184.329239,2059.674454,2613.605421,2536.400502
1,ZMB,Zambia,359.429501,396.548953,393.864626,446.290105,548.685975,710.982068,1051.717149,1118.731626,...,1820.718548,1707.485731,1295.877887,1239.085279,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101
2,YEM,"Yemen, Rep.",493.235183,487.141258,513.241487,548.905883,627.632023,734.159908,809.713128,890.305768,...,1378.750030,1430.164210,1362.173812,975.359417,811.165970,633.887202,NaN,NaN,NaN,NaN
3,PSE,West Bank and Gaza,1476.171850,1335.553195,1156.217473,1257.698570,1422.190886,1543.701414,1570.104400,1664.245717,...,3315.297539,3352.112595,3272.154324,3527.613824,3620.360487,3562.330943,3656.858271,3233.568638,3678.635657,3799.955270
4,VIR,Virgin Islands (U.S.),NaN,NaN,30062.022505,31731.256624,35006.361440,40828.746093,41377.146601,44158.505404,...,34597.976694,33045.364380,34007.352941,35324.974887,35365.069304,36663.208755,38633.529892,39787.374165,42571.077737,44320.909186

In [13]:
# Filter to our 12 countries
our_countries = ['United States', 'France', 'Japan', 'United Arab Emirates',
                 'Brazil', 'Mexico', 'Korea, Rep.',
                 'Vietnam', 'Nigeria', 'Ghana',
                 'Ethiopia', 'Kenya']

gdp_panel = gdp_wb[gdp_wb['Country'].isin(our_countries)].copy()
gdp_panel = gdp_panel.reset_index(drop=True)

print("Countries found:", gdp_panel['Country'].nunique())
gdp_panel[['Country', '2000', '2010', '2022']].round(0)

Countries found: 11

                 Country     2000     2010     2022
0          United States  36330.0  48643.0  76657.0
1   United Arab Emirates  29866.0  44795.0  50760.0
2                Nigeria    547.0   2202.0   2899.0
3                 Mexico   7524.0   9729.0  11406.0
4            Korea, Rep.  12710.0  24071.0  34822.0
5                  Kenya    415.0   1092.0   2110.0
6                  Japan  39169.0  44968.0  34066.0
7                  Ghana    254.0   1264.0   2230.0
8                 France  22341.0  40695.0  40989.0
9               Ethiopia    122.0    331.0    982.0
10                Brazil   3767.0  11403.0   9281.0

---
## Part 5: Selecting Columns and Rows

In [14]:
# Selecting a single column — returns a Series
gdp_col = df['gdp_per_capita']
print(type(gdp_col))
print(gdp_col)

<class 'pandas.core.series.Series'>
0     76399.0
1     40886.0
2     33815.0
3     49532.0
4      9000.5
5      9926.0
6     32255.0
7      4163.5
8      2065.8
9      2363.0
10      925.1
11     1838.0
Name: gdp_per_capita, dtype: float64

In [15]:
# Selecting multiple columns — returns a DataFrame
subset = df[['country', 'gdp_per_capita', 'poverty_rate']]
subset

        country  gdp_per_capita  poverty_rate
0           USA         76399.0           1.2
1        France         40886.0           0.1
2         Japan         33815.0           0.7
3           UAE         49532.0           0.0
4        Brazil          9000.5           5.8
5        Mexico          9926.0           7.3
6   South Korea         32255.0           0.2
7       Vietnam          4163.5           1.5
8       Nigeria          2065.8          39.1
9         Ghana          2363.0          24.8
10     Ethiopia           925.1          26.1
11        Kenya          1838.0          36.1

In [16]:
# .loc — select by LABEL (row index label, column name)
print("Row 0 (USA):")
print(df.loc[0])
print()
print("USA's GDP per capita:")
print(df.loc[0, 'gdp_per_capita'])

Row 0 (USA):
country                     USA
region            North America
income_group               High
gdp_per_capita          76399.0
population            333271341
poverty_rate                1.2
growth_rate                 2.0
year                       2022
Name: 0, dtype: object

USA's GDP per capita:
76399.0

In [17]:
# .iloc — select by POSITION (integer index)
print("First 3 rows, first 3 columns:")
df.iloc[0:3, 0:3]

First 3 rows, first 3 columns:

  country         region income_group
0     USA  North America         High
1  France         Europe         High
2   Japan      East Asia         High

In [18]:
# Set country as the index for more intuitive access
df_indexed = df.set_index('country')

# Now access by country name directly
print("Nigeria's data:")
print(df_indexed.loc['Nigeria'])
print()
print("Nigeria's poverty rate:", df_indexed.loc['Nigeria', 'poverty_rate'])

Nigeria's data:
region            Sub-Saharan Africa
income_group            Lower-Middle
gdp_per_capita                2065.8
population                 218541000
poverty_rate                    39.1
growth_rate                      3.2
year                            2022
Name: Nigeria, dtype: object

Nigeria's poverty rate: 39.1

---
## Part 6: Filtering Rows

Filtering in Pandas works exactly like NumPy boolean indexing — but with column names.

In [19]:
# Countries with poverty rate above 20%
high_poverty = df[df['poverty_rate'] > 20]
high_poverty[['country', 'region', 'poverty_rate', 'gdp_per_capita']]

     country              region  poverty_rate  gdp_per_capita
8    Nigeria  Sub-Saharan Africa          39.1          2065.8
9      Ghana  Sub-Saharan Africa          24.8          2363.0
10  Ethiopia  Sub-Saharan Africa          26.1           925.1
11     Kenya  Sub-Saharan Africa          36.1          1838.0

In [20]:
# Low-income countries only
low_income = df[df['income_group'] == 'Low']
low_income[['country', 'gdp_per_capita', 'poverty_rate', 'growth_rate']]

     country  gdp_per_capita  poverty_rate  growth_rate
10  Ethiopia           925.1          26.1          7.0
11     Kenya          1838.0          36.1          5.2

In [21]:
# Combined: Sub-Saharan Africa AND GDP per capita above $1,500
ssa_above_threshold = df[
    (df['region'] == 'Sub-Saharan Africa') &
    (df['gdp_per_capita'] > 1500)
]
ssa_above_threshold[['country', 'gdp_per_capita', 'poverty_rate']]

    country  gdp_per_capita  poverty_rate
8   Nigeria          2065.8          39.1
9     Ghana          2363.0          24.8
11    Kenya          1838.0          36.1

In [22]:
# .isin() — filter by a list of values
east_asia = df[df['region'].isin(['East Asia'])]
east_asia[['country', 'gdp_per_capita', 'growth_rate']]

       country  gdp_per_capita  growth_rate
2        Japan         33815.0          1.5
6  South Korea         32255.0          2.7
7      Vietnam          4163.5          6.1

In [23]:
# .query() — SQL-style filtering, very readable
result = df.query("poverty_rate < 5 and gdp_per_capita < 50000")
result[['country', 'income_group', 'gdp_per_capita', 'poverty_rate']]

       country  income_group  gdp_per_capita  poverty_rate
1       France          High         40886.0           0.1
2        Japan          High         33815.0           0.7
3          UAE          High         49532.0           0.0
6  South Korea          High         32255.0           0.2
7      Vietnam  Lower-Middle          4163.5           1.5

---
## Part 7: Sorting and Ranking

In [24]:
# Sort by GDP per capita — richest to poorest
df.sort_values('gdp_per_capita', ascending=False)[['country', 'gdp_per_capita', 'income_group']]

        country  gdp_per_capita  income_group
0           USA         76399.0          High
3           UAE         49532.0          High
1        France         40886.0          High
2         Japan         33815.0          High
6   South Korea         32255.0          High
5        Mexico          9926.0  Upper-Middle
4        Brazil          9000.5  Upper-Middle
7       Vietnam          4163.5  Lower-Middle
9         Ghana          2363.0  Lower-Middle
8       Nigeria          2065.8  Lower-Middle
11        Kenya          1838.0           Low
10     Ethiopia           925.1           Low

In [25]:
# Sort by poverty rate — worst to best
df.sort_values('poverty_rate', ascending=False)[['country', 'poverty_rate', 'region']]

        country  poverty_rate              region
8       Nigeria          39.1  Sub-Saharan Africa
11        Kenya          36.1  Sub-Saharan Africa
10     Ethiopia          26.1  Sub-Saharan Africa
9         Ghana          24.8  Sub-Saharan Africa
5        Mexico           7.3       Latin America
4        Brazil           5.8       Latin America
7       Vietnam           1.5           East Asia
0           USA           1.2       North America
2         Japan           0.7           East Asia
6   South Korea           0.2           East Asia
1        France           0.1              Europe
3           UAE           0.0         Middle East

In [26]:
# Multi-column sort: first by region, then by GDP within region
df.sort_values(['region', 'gdp_per_capita'], ascending=[True, False])[['country', 'region', 'gdp_per_capita']]

        country              region  gdp_per_capita
2         Japan           East Asia         33815.0
6   South Korea           East Asia         32255.0
7       Vietnam           East Asia          4163.5
1        France              Europe         40886.0
5        Mexico       Latin America          9926.0
4        Brazil       Latin America          9000.5
3           UAE         Middle East         49532.0
0           USA       North America         76399.0
9         Ghana  Sub-Saharan Africa          2363.0
8       Nigeria  Sub-Saharan Africa          2065.8
11        Kenya  Sub-Saharan Africa          1838.0
10     Ethiopia  Sub-Saharan Africa           925.1

In [27]:
# Add a rank column
df['gdp_rank']     = df['gdp_per_capita'].rank(ascending=False).astype(int)
df['poverty_rank'] = df['poverty_rate'].rank(ascending=True).astype(int)  # lower poverty = better rank

df[['country', 'gdp_per_capita', 'gdp_rank', 'poverty_rate', 'poverty_rank']].sort_values('gdp_rank')

        country  gdp_per_capita  gdp_rank  poverty_rate  poverty_rank
0           USA         76399.0         1           1.2             5
3           UAE         49532.0         2           0.0             1
1        France         40886.0         3           0.1             2
2         Japan         33815.0         4           0.7             4
6   South Korea         32255.0         5           0.2             3
5        Mexico          9926.0         6           7.3             8
4        Brazil          9000.5         7           5.8             7
7       Vietnam          4163.5         8           1.5             6
9         Ghana          2363.0         9          24.8             9
8       Nigeria          2065.8        10          39.1            12
11        Kenya          1838.0        11          36.1            11
10     Ethiopia           925.1        12          26.1            10

---
## Part 8: Adding and Modifying Columns

In [28]:
# Total GDP = GDP per capita × population
df['gdp_total_bn'] = (df['gdp_per_capita'] * df['population'] / 1e9).round(1)

# Log GDP per capita — standard in development economics regressions
df['log_gdp'] = np.log(df['gdp_per_capita']).round(3)

# Projected GDP per capita in 10 years
df['gdp_2032'] = (df['gdp_per_capita'] * (1 + df['growth_rate']/100) ** 10).round(0)

df[['country', 'gdp_per_capita', 'gdp_total_bn', 'log_gdp', 'gdp_2032']]

        country  gdp_per_capita  gdp_total_bn  log_gdp  gdp_2032
0           USA         76399.0       25461.6   11.244   93130.0
1        France         40886.0        2776.0   10.619   52338.0
2         Japan         33815.0        4231.1   10.429   39244.0
3           UAE         49532.0         489.9   10.810   69870.0
4        Brazil          9000.5        1937.9    9.105   12096.0
5        Mexico          9926.0        1265.6    9.203   12706.0
6   South Korea         32255.0        1665.3   10.381   42102.0
7       Vietnam          4163.5         405.8    8.334    7527.0
8       Nigeria          2065.8         451.5    7.633    2831.0
9         Ghana          2363.0          76.6    7.768    3431.0
10     Ethiopia           925.1         114.1    6.830    1820.0
11        Kenya          1838.0          99.3    7.516    3051.0

In [29]:
# Categorical column: classify countries by poverty severity
def poverty_category(rate):
    if rate < 2:
        return 'Very Low'
    elif rate < 10:
        return 'Low'
    elif rate < 25:
        return 'Moderate'
    else:
        return 'High'

df['poverty_category'] = df['poverty_rate'].apply(poverty_category)
df[['country', 'poverty_rate', 'poverty_category']]

        country  poverty_rate poverty_category
0           USA           1.2         Very Low
1        France           0.1         Very Low
2         Japan           0.7         Very Low
3           UAE           0.0         Very Low
4        Brazil           5.8              Low
5        Mexico           7.3              Low
6   South Korea           0.2         Very Low
7       Vietnam           1.5         Very Low
8       Nigeria          39.1             High
9         Ghana          24.8         Moderate
10     Ethiopia          26.1             High
11        Kenya          36.1             High

In [30]:
# np.where — vectorized if-else
df['fast_grower'] = np.where(df['growth_rate'] >= 5, 'Yes', 'No')
df[['country', 'growth_rate', 'fast_grower']]

        country  growth_rate fast_grower
0           USA          2.0          No
1        France          2.5          No
2         Japan          1.5          No
3           UAE          3.5          No
4        Brazil          3.0          No
5        Mexico          2.5          No
6   South Korea          2.7          No
7       Vietnam          6.1         Yes
8       Nigeria          3.2          No
9         Ghana          3.8          No
10     Ethiopia          7.0         Yes
11        Kenya          5.2         Yes

---
## Part 9: Saving and Loading Data

In [31]:
# Save to CSV — you will use this across all future lectures
df.to_csv('development_data.csv', index=False)
print("Saved to development_data.csv")

Saved to development_data.csv

In [32]:
# Load it back
df_loaded = pd.read_csv('development_data.csv')
print("Loaded shape:", df_loaded.shape)
df_loaded.head(3)

Loaded shape: (12, 15)

,country,region,income_group,gdp_per_capita,population,poverty_rate,growth_rate,year,gdp_rank,poverty_rank,gdp_total_bn,log_gdp,gdp_2032,poverty_category,fast_grower
0,USA,North America,High,76399.0,333271341,1.2,2.0,2022,1,5,25461.6,11.244,93130.0,Very Low,No
1,France,Europe,High,40886.0,67897000,0.1,2.5,2022,3,2,2776.0,10.619,52338.0,Very Low,No
2,Japan,East Asia,High,33815.0,125124989,0.7,1.5,2022,4,4,4231.1,10.429,39244.0,Very Low,No

---
## 📌 Summary

| Task | Method |
|------|--------|
| Create DataFrame | `pd.DataFrame(dict)` |
| Inspect | `.shape`, `.dtypes`, `.describe()`, `.isnull()` |
| Select column | `df['col']` or `df[['col1','col2']]` |
| Select by label | `df.loc[row, col]` |
| Select by position | `df.iloc[row, col]` |
| Filter rows | `df[df['col'] > value]` |
| SQL-style filter | `df.query("col > value")` |
| Sort | `df.sort_values('col')` |
| Add column | `df['new'] = ...` |
| Apply function | `df['col'].apply(func)` |
| Save | `df.to_csv('file.csv')` |
| Load | `pd.read_csv('file.csv')` |

**Next lecture:** Pandas II — groupby, merging, reshaping, and cleaning messy data.

---
*ECON N171 | Summer 2026*